# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
before_install:
- sudo apt install -y libudunits2-0 libudunits2-dev
- sudo apt install libgdal-dev

language: R
cache: packages

after_success:
    - Rscript -e 'covr::codecov()'

